#!/bin/bash
#imwheel -k
$HOME/Scripts/disablemouseaccel.sh
xhost si:localuser:root
setxkbmap -option caps:escape
nvidia-settings -a "[gpu:0]/GPUFanControlState=1" -a "[fan:0]/GPUTargetFanSpeed=30"
#sudo $HOME/Scripts/timesync.sh
